{
 "title": "mindra-rag-app",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "rag_active_session",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_active_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "rag_requests_total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "rag_requests_created",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 5 },
   "targets": [
    { "expr": "rag_requests_created", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "rag_response_time_seconds_created",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "rag_response_time_seconds_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rag_response_time_seconds_sum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_response_time_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "rag_response_time_seconds_count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rag_response_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}